tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "mongodb/brew"
brew "fd"
brew "fzf"
brew "starship"
brew "yarn"
brew "mongodb/brew/mongodb-community"
brew "mas"
brew "iconsur"
brew "unar"
brew "pyenv"
brew "xz"
cask "visual-studio-code"
cask "google-chrome"
cask "hey"
cask "zoom"
cask "spline"
cask "figma"
mas "Bear Markdown Notes", id: 1091189122
mas "Kindle", id: 302584613
mas "Slack for Desktop", id: 803453959  
