tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-versions"
tap "mongodb/brew"
brew "fd"
brew "fzf"
brew "starship"
brew "yarn"
brew "mongodb/brew/mongodb-community"
brew "mas"
brew "iconsur"
cask "visual-studio-code"
cask "google-chrome"
cask "hey"
cask "topnotch"
cask "linear-linear"
cask "figma"
mas "AdGuard for Safari", id: 1440147259
mas "Logic Pro", id: 634148309
mas "Balance: Mindful time tracking", id: 1637311725  
