tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "bat"
brew "fd"
brew "fzf"
brew "jq"
brew "python@3.9"
brew "ripgrep"
brew "starship"
brew "wget"
brew "yarn"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
brew "luajit", args: [ "build-from-source" ]
cask "syncthing"

